
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 17 12:43:33 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 10;
  public static final int CONST = 12;
  public static final int CHAR = 18;
  public static final int GRT = 28;
  public static final int LPAREN = 42;
  public static final int SEMI = 37;
  public static final int LESS = 30;
  public static final int MINUS = 22;
  public static final int RPAREN = 43;
  public static final int GREQ = 29;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 39;
  public static final int BOOL = 19;
  public static final int CLASS = 3;
  public static final int INC = 35;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int ASSIGN = 34;
  public static final int IF = 5;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int LESEQ = 31;
  public static final int FOREA = 8;
  public static final int NUMBER = 17;
  public static final int MOD = 25;
  public static final int NEQ = 27;
  public static final int BREAK = 9;
  public static final int IDENT = 20;
  public static final int VOID = 11;
  public static final int EQ = 26;
  public static final int LBRACK = 44;
  public static final int COL = 38;
  public static final int ARROW = 41;
  public static final int LBRACE = 46;
  public static final int ELSE = 6;
  public static final int RBRACK = 45;
  public static final int READ = 14;
  public static final int WHILE = 7;
  public static final int RBRACE = 47;
  public static final int PROG = 2;
  public static final int DEC = 36;
  public static final int PRINT = 15;
  public static final int EXTE = 4;
}

